"""first

Revision ID: 595e84017e2b
Revises: 
Create Date: 2021-08-18 19:04:32.390703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '595e84017e2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
